version: '3.4'
services:
  push-tf-secondary-1:
    container_name: "push-tf-secondary-1"
    hostname: "push-tf-secondary-1"
    tty: true
    image: eismcc/push-${PUSH_DEPLOY_TYPE}-tensorflow-gpu:latest
    expose:
      - '10001'
      - '11001'
      - '50001'
    env_file:
      - ../envs/push.env
    volumes:
      - ../conf/push.bootstrap.conf.yml:/opt/push/conf/push.conf.yml
      - $PUSH_HOME:/scm/push
    command: ["push_server", "/opt/push/conf/push.conf.yml"]
    network_mode: host
