version: '1'
bootstrap:
    boot_source_uri: 'file:///scm/push/pushpy_examples/boot/ex_boot.py'
hostname: 'push-tf-3'
manager:
    auth_key: 'password'
sync_obj:
    port: 10000
    peers:
        - push-tf-1:10000
        - push-tf-2:10000

